version: '3.8'

services:
  api:
    build: ./FurryFootsteps-API
    env_file:
      - FurryFootsteps-API/.env
    depends_on:
      - database
    ports:
      - '8090:8080'

  pgadmin:
    image: 'elestio/pgadmin'
    env_file:
      - FurryFootsteps-API/.env
    ports:
      - '5050:5050'
    volumes:
      - ./FurryFootsteps-API/servers.json:/pgadmin4/servers.json

  database:
    image: 'postgres'
    env_file:
      - FurryFootsteps-API/.env
    ports:
      - '5432:5432'
    volumes:
      - ./FurryFootsteps-API/init.sql:/docker-entrypoint-initdb.d/init.sql



