version: '3.8'

services:
  api:
    build: ./FurryFootsteps-API
    env_file:
      - FurryFootsteps-API/.env
    depends_on:
      - database
    ports:
      - '8090:8080'

  pgadmin:
    image: 'dpage/pgadmin4:6.7'
    env_file:
      - FurryFootsteps-API/.env
    ports:
      - '5050:5050'

  database:
    image: 'postgres:16-alpine3.18'
    env_file:
      - FurryFootsteps-API/.env
    ports:
      - '5432'

